### ISSUE TITLE
T11-0089.xls is missing

### ISSUE THREAD

**Issue by aaronferrucci** [wmurphyrd/BernieTax#1]
I wanted to try reproducing your chart, but I found that T11-0089.xls is missing. Can you provide it, or a link to it?

**Comment by wmurphyrd** [comment]
That file isn't used in the final version, but I had failed to remove the line that accessed it. Just pushed a commit that has the line removed and it should run now. 

Thanks.

**Comment by aaronferrucci** [comment]
Thanks, works great. And thanks for making your research reproducible!
