### ISSUE TITLE
Mind doing this for a single income, no dependent POV?

### ISSUE THREAD

**Issue by aguynamedjoetoo** [wmurphyrd/BernieTax#3]
I've done the changes in bernietax.R on my fork:

https://github.com/Joeskyyy/BernieTax/blob/master/bernietax.R

Would love to see how this kind of stuff affects those of us who are filing single, and don't have kids.

**Comment by aguynamedjoetoo** [comment]
Gonna close this out, did the compiling myself and it's still interesting. Would be good if there were multiple graphs.

Great work on this @wmurphyrd ! and thank you for open sourcing it.

**Comment by wmurphyrd** [comment]
@Joeskyyy , I'm very interested in adding options to different family units and moving towards an interactive. In addition to the deduction changes I see in your code, I also need to track down estimates of healthcare premiums and out of pocket expenses for singles and couples.
