### ISSUE TITLE
'incomeBracketsCurrent' Does not take into account initial tax amount before percentages kicks in

### ISSUE THREAD

**Issue by aguynamedjoetoo** [wmurphyrd/BernieTax#4]
Looking at: https://www.irs.com/articles/2015-federal-tax-rates-personal-exemptions-and-standard-deductions

Let's take a family in the $18,451 to $74,900 bracket making $30,000

That family would be paying $1,845.00 in taxes, and 15% of the income over $18,450 (In this case $11,500 of more taxable income).

If I'm looking at the calculations correctly, bernietax.R would only compute this as a raw 15%, so in this case $4,500. When in reality it should be $1,8450 + ($11,500 \* 15%), bringing the total to $6225 of income tax for that bracket.

Am I missing a portion of the code where this is considered? Or am I analysing the IRS site wrong, either could be completely possible ;P

**Comment by wmurphyrd** [comment]
Thanks for checking my math! Take a look at the function `tax`. Try calling it directly with a single bracket and a vector of incomes to experiment with the computed tax for each income level. 

`tax(incomeBracketsCurrent, c(18450, 30000), 0)`

`[1] 1845.0 3577.5`

It breaks down the total income by brackets and applies the appropriate rate to each portion. 

(P.S. $1,845 + ($11,550 \* 15%) = $3,577.50 )

**Comment by aguynamedjoetoo** [comment]
Figures I'd miss something (: thanks for responding!
